# Generated by Django 5.2.5 on 2025-11-25 10:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(default='Cruz Verde', editable=False, max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('REGIÓN DE ARICA Y PARINACOTA', 'Arica y Parinacota'), ('REGIÓN DE TARAPACÁ', 'Tarapacá'), ('REGIÓN DE ANTOFAGASTA', 'Antofagasta'), ('REGIÓN DE ATACAMA', 'Atacama'), ('REGIÓN DE COQUIMBO', 'Coquimbo'), ('REGIÓN DE VALPARAÍSO', 'Valparaíso'), ('REGIÓN METROPOLITANA DE SANTIAGO', 'Metropolitana de Santiago'), ('REGIÓN DE O HIGGINS', 'O Higgins'), ('REGIÓN DEL MAULE', 'Maule'), ('REGIÓN DE ÑUBLE', 'Ñuble'), ('REGIÓN DEL BIOBÍO ', 'Biobío'), ('REGIÓN DE LA ARAUCANÍA', 'Araucanía'), ('REGIÓN DE LOS RÍOS', 'Ríos'), ('REGIÓN DE LOS LAGOS', 'Lagos'), ('REGIÓN DE AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO', 'Aysén del General Carlos Ibáñez del Campo'), ('REGIÓN DE MAGALLANES Y LA ANTÁRTICA CHILENA', 'Magallanes y la Antártica Chilena')], default='REGIÓN METROPOLITANA DE SANTIAGO', help_text='Seleccione una o más regiones, separadas por coma', max_length=500)),
                ('comuna', models.CharField(max_length=100)),
                ('horario_recepcion_inicio', models.TimeField(help_text='Hora de inicio de la ventana de recepción (HH:MM:SS).')),
                ('horario_recepcion_fin', models.TimeField(help_text='Hora de fin de la ventana de recepción (HH:MM:SS).')),
                ('dias_operativos', models.CharField(help_text='Seleccione los días de la semana en que la farmacia recibe despachos. Guardado como coma separado.', max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='farmacias/')),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=50, unique=True)),
                ('patente', models.CharField(max_length=16, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('anio_fabricacion', models.IntegerField(blank=True, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=60, null=True)),
                ('permiso_circulacion_vigente', models.BooleanField(default=False)),
                ('revision_tecnica_vigente', models.BooleanField(default=False)),
                ('consumo_combustible', models.DecimalField(blank=True, decimal_places=2, help_text='L/100km', max_digits=5, null=True)),
                ('capacidad_carga', models.DecimalField(blank=True, decimal_places=2, help_text='En Kg', max_digits=6, null=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('OCUPADO', 'Ocupado'), ('EN_TALLER', 'En Taller'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='OPERATIVO', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('velocidad_promedio', models.DecimalField(blank=True, decimal_places=2, help_text='Km/h', max_digits=5, null=True)),
                ('frenadas_bruscas', models.PositiveIntegerField(default=0, help_text='Por día')),
                ('aceleraciones_rapidas', models.PositiveIntegerField(default=0, help_text='Por día')),
                ('tiempo_inactividad_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Horas', max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=16, unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('emergencia_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('licencia_tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('licencia_vigente', models.BooleanField(default=False)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_DESPACHO', 'En Despacho'), ('EN_DESCANSO', 'En Descanso'), ('CON_LICENCIA', 'Con Licencia'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('posesion_moto', models.CharField(choices=[('SIN_MOTO', 'Sin Moto'), ('CON_MOTO', 'Con Moto')], default='SIN_MOTO', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motoristas/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('tipo_servicio', models.CharField(max_length=60)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='App.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=50, unique=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_toma_pedido', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_salida_farmacia', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_estimada_llegada', models.DateTimeField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('INCIDENCIA', 'Incidencia'), ('ANULADO', 'Anulado'), ('REENVIO', 'Reenvío')], default='PENDIENTE', max_length=20)),
                ('incidencia_motivo', models.TextField(blank=True, null=True)),
                ('incidencia_fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('motivo_reenvio', models.TextField(blank=True, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('DIRECTO', 'Directo'), ('CON_RECETA', 'Con Receta'), ('CON_TRASLADO', 'Con Traslado'), ('REENVIO', 'Reenvío')], max_length=20)),
                ('numero_receta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision_receta', models.DateField(blank=True, null=True)),
                ('medico_prescribiente', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_edad', models.IntegerField(blank=True, null=True)),
                ('tipo_establecimiento_traslado', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='despachos/')),
                ('farmacia_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmacia')),
                ('motorista_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.motorista')),
            ],
            options={
                'permissions': [('can_view_dashboard_general', 'Puede ver el dashboard general'), ('can_view_dashboard_regional', 'Puede ver el dashboard regional'), ('can_export_csv', 'Puede exportar CSV'), ('can_export_pdf', 'Puede exportar PDF')],
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField()),
                ('numero_lote', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=60, null=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='App.despacho')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('MOTORISTA', 'Motorista')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportDownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(max_length=50)),
                ('filter_type', models.CharField(blank=True, max_length=20, null=True)),
                ('filter_date', models.DateField(blank=True, null=True)),
                ('filter_month', models.CharField(blank=True, max_length=7, null=True)),
                ('filter_year', models.PositiveIntegerField(blank=True, null=True)),
                ('motorista_id', models.CharField(blank=True, max_length=100, null=True)),
                ('format', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'MOTORISTA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AsignacionMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.moto')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.motorista')),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('motorista',), name='motorista_una_asignacion_activa1'), models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('moto',), name='moto_una_asignacion_activa1')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmacia')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.motorista')),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('motorista',), name='motorista_una_asignacion_activa2')],
            },
        ),
    ]
