# Generated by Django 5.2.7 on 2025-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarMotorista',
            fields=[
                ('idasignacion', models.AutoField(db_column='idAsignacion', primary_key=True, serialize=False)),
                ('fechaasignacion', models.DateTimeField(blank=True, db_column='fechaAsignacion', null=True)),
                ('fechadesasignacion', models.DateTimeField(blank=True, db_column='fechaDesasignacion', null=True)),
                ('activa', models.IntegerField(blank=True, default=1)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'asignar_motorista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('idfarmacia', models.AutoField(db_column='idFarmacia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('horarioapertura', models.TimeField(blank=True, db_column='horarioApertura', null=True)),
                ('horariocierre', models.TimeField(blank=True, db_column='horarioCierre', null=True)),
                ('activa', models.IntegerField(blank=True, default=1)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'farmacia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('idmoto', models.AutoField(db_column='idMoto', primary_key=True, serialize=False)),
                ('patente', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('numerochasis', models.CharField(blank=True, db_column='numeroChasis', default='', max_length=50, unique=True)),
                ('numeromotor', models.CharField(blank=True, db_column='numeroMotor', default='', max_length=50)),
                ('aniodocumentacion', models.IntegerField(blank=True, db_column='anioDocumentacion', null=True)),
                ('aniopermisocirculacion', models.IntegerField(blank=True, db_column='anioPermisoCirculacion', null=True)),
                ('seguroobligatorio', models.DateField(blank=True, db_column='seguroObligatorio', null=True)),
                ('revisiontecnica', models.DateField(blank=True, db_column='revisionTecnica', null=True)),
                ('propietario', models.CharField(blank=True, default='', max_length=9)),
                ('disponible', models.IntegerField(blank=True, default=1)),
                ('activa', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'moto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('idmotorista', models.AutoField(db_column='idMotorista', primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, default='', max_length=12, unique=True)),
                ('pasaporte', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('apellidopaterno', models.CharField(blank=True, db_column='apellidoPaterno', default='', max_length=100)),
                ('apellidomaterno', models.CharField(blank=True, db_column='apellidoMaterno', default='', max_length=100)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('licenciaconducir', models.CharField(blank=True, db_column='licenciaConducir', default='', max_length=20, unique=True)),
                ('licenciaarchivo', models.CharField(blank=True, db_column='licenciaArchivo', default='', max_length=255)),
                ('fechaultimocontrol', models.DateField(blank=True, db_column='fechaUltimoControl', null=True)),
                ('fechaproximocontrol', models.DateField(blank=True, db_column='fechaProximoControl', null=True)),
                ('fechacontratacion', models.DateField(blank=True, db_column='fechaContratacion', null=True)),
                ('activo', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'motorista',
                'managed': False,
            },
        ),
    ]
